### ISSUE TITLE
PettingZoo

### ISSUE THREAD

**Issue by jkterry1** [dellalibera/gym-backgammon#1]
Hey, I just wanted to mention that we used your code as the base logic of the Backgammon environment PettingZoo, a library that we just released (https://github.com/PettingZoo-Team/PettingZoo / https://www.pettingzoo.ml/). I credited you in the code, and we really appreciate your work.

**Comment by ndvbd** [comment]
@jkterry1 Hi Jordan, is the backgammon environment available in PettingZoo?

**Comment by jkterry1** [comment]
We eventually removed it because it was being so rarely used (and I believe may have had bugs). It's available in older versions if you look back through the release notes if you'd like to try it out though, and if you want to maintain your own version of it for pettingzoo, we'd be happy to link to the github repo in the third party repos list in the pettingzoo documentation website
